In [23]:
import numpy as np

def load_sift_binary(file_path):
    try:
        with open(file_path, 'rb') as f:
            # Skip the header (16 bytes)
            f.seek(16)

            # Read the number of keypoints
            num_keypoints = np.fromfile(f, dtype=np.int32, count=1)[0]
            print(f"Number of keypoints: {num_keypoints}")

            # Skip extra bytes after the keypoint count (the next 64 bytes)
            extra_data_size = 64
            f.seek(extra_data_size, 1)  # Skip the extra data after the keypoint count
            
            # Read keypoints (x, y, scale, orientation)
            keypoints = np.fromfile(f, dtype=np.float32, count=num_keypoints * 4).reshape(-1, 4)

            # Read descriptors (128-dimensional vector for each keypoint)
            descriptors = np.fromfile(f, dtype=np.float32, count=num_keypoints * 128).reshape(-1, 128)

            return keypoints, descriptors
    except ValueError as e:
        print(f"Error processing the binary file: {e}")
        return None, None

# Path to the binary .sift file
file_path = 'frame_0000.sift'

# Load the data
keypoints, descriptors = load_sift_binary(file_path)

if keypoints is not None and descriptors is not None:
    print(f"Loaded {len(keypoints)} keypoints and {len(descriptors)} descriptors for {file_path[:-5]}")
    print("5 sample Keypoints: [x, y, scale, orientation] \n", keypoints[:5])  # Print the first 5 keypoints
    # print("Sample Descriptors:\n", descriptors[:1])  # Print the first 5 descriptors


Number of keypoints: 128
Loaded 128 keypoints and 128 descriptors for frame_0000
5 sample Keypoints: [x, y, scale, orientation] 
 [[ 4.0590130e+01  2.0747987e-38  2.4804729e+01 -3.5830009e+00]
 [ 5.4456128e+02  6.2653938e+01  2.2956706e-38  2.4218735e+01]
 [-5.3122315e+00  5.4456128e+02  6.2653938e+01  2.2956706e-38]
 [ 2.4218735e+01 -3.3239183e+00  4.0976184e+02  2.5699390e+02]
 [ 1.4389019e-38  2.2769594e+01 -9.3949968e-01  4.0976184e+02]]


In [25]:
import cv2
cv2.xfeatures2d.readSIFT(file_path)

AttributeError: module 'cv2.xfeatures2d' has no attribute 'readSIFT'